# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sourcegraph < Formula
  desc "Code intelligence and search"
  homepage "https://github.com/sourcegraph/sourcegraph"
  version "0.0.196384-snapshot+20230131-6902ad"
  license "Sourcegraph Enterprise License (portions licensed under Apache 2)"

  depends_on "git"
  depends_on "redis"
  depends_on "sourcegraph/src-cli/src-cli"

  on_macos do
    if Hardware::CPU.intel?
      url "https://storage.googleapis.com/sourcegraph-app-releases/0.0.196384-snapshot+20230131-6902ad/sourcegraph_0.0.196384-snapshot+20230131-6902ad_darwin_amd64.zip"
      sha256 "50159fe11d8bd432fea23c04782cf9c3e74853a7a1988fef15d0d13928257416"

      def install
        bin.install "sourcegraph"
      end
    end
    if Hardware::CPU.arm?
      url "https://storage.googleapis.com/sourcegraph-app-releases/0.0.196384-snapshot+20230131-6902ad/sourcegraph_0.0.196384-snapshot+20230131-6902ad_darwin_arm64.zip"
      sha256 "93e4b9682e2f9847edb7f43e59b10e869a8abb3fae8c6eef50bc0f07aaa1bb97"

      def install
        bin.install "sourcegraph"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://storage.googleapis.com/sourcegraph-app-releases/0.0.196384-snapshot+20230131-6902ad/sourcegraph_0.0.196384-snapshot+20230131-6902ad_linux_amd64.zip"
      sha256 "4785209e58e282c4585087d97a598f42aac569b3f1949aeef414626f355c8ecd"

      def install
        bin.install "sourcegraph"
      end
    end
  end

  test do
    system "#{bin}/sourcegraph --help"
  end
end
